[tool.uv.sources]
hozon-watcher = { workspace = true }

[tool.uv.workspace]
members = ["modules/*", "packages/*"]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
    "ty>=0.0.1a20",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
